import Header from "@/components/Header"
import "../app/css/global.css"
import type { Metadata } from 'next'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en"> 
      <body className="font-bodyFont">
        <Header/>
        {children}
        </body>
    </html>
  )
}
